---
- hosts: webservers
  remote_user: sshable

  tasks:
  - name: copy static files
    copy:
      src: index.html
      dest: /data/www/index.html
      owner: swacat
      group: nginx
      mode: 0775
    become: yes
    become_user: swacat
